spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:7432/cart-db
    username: shopping-cart
    password: shopping-cart
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate:
      jdbc.time_zone: UTC
      format_sql: true
      temp.use_jdbc_metadata_defaults: false
    hibernate.ddl-auto: update
    show-sql: true
  sql.init.mode: always

server:
  port: 0

logging:
  level:
    org:
      springframework: INFO
      apache.kafka: WARN
